### ISSUE TITLE
Genereated .breadcrumb > li + li:before has double escaped `content`

### ISSUE THREAD

**Issue by gniquil** [lifegadget/ember-cli-bootstrap-sassy#22]
Not sure if I am the only one having this problem, but if you use breadcrumbs, rather than showing as "/", you will see the separator as "/\00a0". The original bootstrap sass contains the breadcrumb.scss file:

``` scss
.breadcrumb {
  padding: $breadcrumb-padding-vertical $breadcrumb-padding-horizontal;
  margin-bottom: $line-height-computed;
  list-style: none;
  background-color: $breadcrumb-bg;
  border-radius: $border-radius-base;

  > li {
    display: inline-block;

    + li:before {
      content: "#{$breadcrumb-separator}\00a0"; // Unicode space added since inline-block means non-collapsing white-space
      padding: 0 5px;
      color: $breadcrumb-color;
    }
  }
...
```

The above is correct. However, the generated code has the single "\" in "\00a0" doubled to "\00a0", hence the error. 

Anyone experience the same problem? Any suggestions for a fix? Is this a broccoli issue?
